services:
  db:
    image: postgres:15-alpine
    container_name: pg_fintech
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fintech
    ports:
      - "5432:5432"
    restart: unless-stopped
